# Copy this file to group_vars/all/secrets.yml and fill in the real values.

weewx_awekas_username: CHANGE_ME
weewx_awekas_password: CHANGE_ME

weewx_cwop_station: GW0000
weewx_cwop_passcode: replace_me

weewx_pwsweather_station: CHANGE_ME
weewx_pwsweather_password: CHANGE_ME

weewx_wow_station: CHANGE_ME
weewx_wow_password: CHANGE_ME

weewx_wunderground_station: CHANGE_ME
weewx_wunderground_password: CHANGE_ME
weewx_wunderground_api_key: replace_me

windy_station_id: CHANGE_ME
windy_station_password: CHANGE_ME
